<a href="https://colab.research.google.com/github/kosukeshirane/-Prog2kakushin/blob/main/work2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NumPy
2人分のBINGOカードをランダムに作成し、BINGO大会を行うプログラムです。
0が揃うことでBINGOしたことにしました。


In [58]:
#BINGOカードをランダムに作成
import numpy as np
from matplotlib import pyplot as plt

def bingo(a, b, k):
  s = []
  while len(s) < k:
    n = np.random.randint(a, b)
    if not [n] in s:
      s.append([n])
  return s
x=1
y=16
l1=np.array(bingo(x,y,5))
l2=np.array(bingo(x,y,5))
for i in range(4):
  x+=15
  y+=15
  l12=np.array(bingo(x,y,5))
  l1=np.append(l1,l12, axis=1)
  l22=np.array(bingo(x,y,5))
  l2=np.append(l2,l22, axis=1)
l1[2,2]=0
l2[2,2]=0
print('1人目\n',l1)
print('2人目\n',l2)

1人目
 [[ 1 25 42 54 74]
 [ 9 27 31 60 61]
 [ 3 26  0 51 75]
 [15 16 35 56 70]
 [11 19 33 50 72]]
2人目
 [[ 7 22 36 57 74]
 [14 29 37 56 69]
 [ 1 27  0 48 75]
 [13 26 34 59 67]
 [15 16 32 58 66]]


In [59]:
#BINGO大会の実施
p = []
while True:
  n = np.random.randint(1, 76)
  if not n in p:
    p.append(n)
    print(n)
  elif n in p:
    continue
  for i in range(5):
    for j in range(5):
      if l1[i,j]==n:
        l1[i,j]=0
      if l2[i,j]==n:
        l2[i,j]=0
  print('1人目\n',l1)
  print('2人目\n',l2)
  if l1[0,0]==0:
    if l1[1,1]==0:
      if l1[3,3]==0:
        if l1[4,4]==0:
          print('BINGO!!!')
          print('1人目の勝ち!!!')
          break
  if l1[0,4]==0:
    if l1[1,3]==0:
      if l1[3,1]==0:
        if l1[4,0]==0:
          print('BINGO!!!')
          print('1人目の勝ち!!!')
          break
  if l2[0,0]==0:
    if l2[1,1]==0:
      if l2[3,3]==0:
        if l2[4,4]==0:
          print('BINGO!!!')
          print('2人目の勝ち!!!')
          break
  if l2[0,4]==0:
    if l2[1,3]==0:
      if l2[3,1]==0:
        if l2[4,0]==0:
          print('BINGO!!!')
          print('2人目の勝ち!!!')
          break
  for h in range(5):
    if l1[h,0]==0:
      if l1[h,1]==0:
        if l1[h,2]==0:
          if l1[h,3]==0:
            if l1[h,4]==0:
              print('BINGO!!!')
              print('1人目の勝ち!!!')
              break
    if l1[0,h]==0:
      if l1[1,h]==0:
        if l1[2,h]==0:
          if l1[3,h]==0:
            if l1[4,h]==0:
              print('BINGO!!!')
              print('1人目の勝ち!!!')
              break
    if l2[h,0]==0:
      if l2[h,1]==0:
        if l2[h,2]==0:
          if l2[h,3]==0:
            if l2[h,4]==0:
              print('BINGO!!!')
              print('2人目の勝ち!!!')
              break
    if l2[0,h]==0:
      if l2[1,h]==0:
        if l2[2,h]==0:
          if l2[3,h]==0:
            if l2[4,h]==0:
              print('BINGO!!!')
              print('2人目の勝ち!!!')
              break
  else:
    continue
  break


29
1人目
 [[ 1 25 42 54 74]
 [ 9 27 31 60 61]
 [ 3 26  0 51 75]
 [15 16 35 56 70]
 [11 19 33 50 72]]
2人目
 [[ 7 22 36 57 74]
 [14  0 37 56 69]
 [ 1 27  0 48 75]
 [13 26 34 59 67]
 [15 16 32 58 66]]
64
1人目
 [[ 1 25 42 54 74]
 [ 9 27 31 60 61]
 [ 3 26  0 51 75]
 [15 16 35 56 70]
 [11 19 33 50 72]]
2人目
 [[ 7 22 36 57 74]
 [14  0 37 56 69]
 [ 1 27  0 48 75]
 [13 26 34 59 67]
 [15 16 32 58 66]]
57
1人目
 [[ 1 25 42 54 74]
 [ 9 27 31 60 61]
 [ 3 26  0 51 75]
 [15 16 35 56 70]
 [11 19 33 50 72]]
2人目
 [[ 7 22 36  0 74]
 [14  0 37 56 69]
 [ 1 27  0 48 75]
 [13 26 34 59 67]
 [15 16 32 58 66]]
26
1人目
 [[ 1 25 42 54 74]
 [ 9 27 31 60 61]
 [ 3  0  0 51 75]
 [15 16 35 56 70]
 [11 19 33 50 72]]
2人目
 [[ 7 22 36  0 74]
 [14  0 37 56 69]
 [ 1 27  0 48 75]
 [13  0 34 59 67]
 [15 16 32 58 66]]
55
1人目
 [[ 1 25 42 54 74]
 [ 9 27 31 60 61]
 [ 3  0  0 51 75]
 [15 16 35 56 70]
 [11 19 33 50 72]]
2人目
 [[ 7 22 36  0 74]
 [14  0 37 56 69]
 [ 1 27  0 48 75]
 [13  0 34 59 67]
 [15 16 32 58 66]]
11
1人目
 [[ 1 25 42 54 74]